# Generated by Django 4.2 on 2026-05-10 20:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App_HotelManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
