# Generated by Django 4.2 on 2026-05-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_HotelManager', '0002_alter_asignacion_fecha_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('limpieza', 'En limpieza')], default='disponible', max_length=20),
        ),
    ]
