# Generated by Django 4.2 on 2026-05-10 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_HotelManager', '0004_usuario_es_cuenta_prueba_usuario_fecha_expiracion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuarios',
        ),
    ]
