# Generated by Django 4.2 on 2026-05-10 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_HotelManager', '0005_alter_usuario_options_alter_usuario_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='es_cuenta_prueba',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_expiracion',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table=None,
        ),
        migrations.DeleteModel(
            name='PerfilUsuario',
        ),
    ]
