# Generated by Django 4.2 on 2026-05-16 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_HotelManager', '0006_alter_usuario_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='moneda',
            field=models.CharField(choices=[('NIO', 'Córdobas'), ('USD', 'Dólares')], default='NIO', max_length=3),
        ),
    ]
