# Generated by Django 4.2 on 2026-05-17 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_HotelManager', '0007_habitacion_moneda'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilhotel',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilhotel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='perfilhotel',
            name='rfc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='perfilhotel',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
