# Generated by Django 4.2 on 2026-05-22 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_HotelManager', '0009_cliente_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habitaciones_creadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
